// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGW3fVZRrYoPu9cUzazsXOsqPOtYFK6w4',
    appId: '1:930272647799:web:b75809be7878cd4893c472',
    messagingSenderId: '930272647799',
    projectId: 'arttrader-d69bb',
    authDomain: 'arttrader-d69bb.firebaseapp.com',
    storageBucket: 'arttrader-d69bb.appspot.com',
    measurementId: 'G-4SFSENETNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IGtUQBdnXUrMjiSFWwJkyqRMpP94iOs',
    appId: '1:930272647799:android:9dca1c3d2f8d9b3993c472',
    messagingSenderId: '930272647799',
    projectId: 'arttrader-d69bb',
    storageBucket: 'arttrader-d69bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqAmx4J3F5Ko_XDHXdmeYOKxJnuqUFEA',
    appId: '1:930272647799:ios:745250b66649dc9393c472',
    messagingSenderId: '930272647799',
    projectId: 'arttrader-d69bb',
    storageBucket: 'arttrader-d69bb.appspot.com',
    iosClientId: '930272647799-e40u98o26fkguck0td2falaghgnajk10.apps.googleusercontent.com',
    iosBundleId: 'com.example.arttrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqAmx4J3F5Ko_XDHXdmeYOKxJnuqUFEA',
    appId: '1:930272647799:ios:2e0b4ed30e8c7d1b93c472',
    messagingSenderId: '930272647799',
    projectId: 'arttrader-d69bb',
    storageBucket: 'arttrader-d69bb.appspot.com',
    iosClientId: '930272647799-bds0bqb4ofo1gf38doeo5q2ad2aa2u68.apps.googleusercontent.com',
    iosBundleId: 'com.example.arttrader.RunnerTests',
  );
}
